name: manualWorkflow

on: 
    workflow_dispatch:
        inputs:
          Environment:
            description: QA Server
            required: true
            default: qa1
            type: choice
            options:
              - qa1
              - qa2
              - qa3
              - qa4

          Test Suite:
            description: Test Run
            required: false
            type: choice
            default: Sanity
            options:
              - Regression
              - Smoke
              - Sanity

jobs: 
    manualJobs:
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses:  actions/checkout@v4

            - name: Set up Node.JS
              uses: actions/setup-node@v4
              with:
                node-version: lts/*
            
            - name: Install dependencies of Playwright
              run: npm ci

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            
            - name: Run the Regression Test Cases
              if: ${{github.event.inputs['Test Suite'] == 'Regression'}}
              run: npx playwright test -g @regression

            - name: Run the Smoke Test Cases
              if: ${{github.event.inputs['Test Suite'] == 'Smoke'}}
              run: npx playwright test -g @smoke

            - name: Run the Sanity Test Cases
              if: ${{github.event.inputs['Test Suite'] == 'Sanity'}}
              run: ENVIRONMENT=${{github.event.inputs['Environment']}} npx playwright test -g @sanity

            - name: Upload the report
              uses: actions/upload-artifact@v4
              if: ${{!cancelled()}}
              with:
                name: playwright-report
                path: playwright-report/
                retention-days: 10
